use_frameworks!

platform :ios, '9.0'

target 'EXCheckCarKit_Example' do
  pod 'EXCheckCarKit', :path => '../'

  target 'EXCheckCarKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
